//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукция()
        {
            this.Газеты = new HashSet<Газеты>();
        }
    
        public int ID { get; set; }
        public string Наименование_продукции { get; set; }
        public Nullable<int> Тип_продукции { get; set; }
        public Nullable<int> Артикул { get; set; }
        public Nullable<int> Кол_во_человек_для_производства { get; set; }
        public Nullable<int> Номер_цеха_производства { get; set; }
        public Nullable<int> Минимальная_цена_для_агента { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Газеты> Газеты { get; set; }
        public virtual ТипПродукции ТипПродукции { get; set; }
    }
}
